// <auto-generated />
using System;
using GreenBook.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenBook.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GreenBookDbContext))]
    partial class GreenBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenBook.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("State")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.CourseHole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("HandicapIndex")
                        .HasColumnType("integer");

                    b.Property<int>("HoleNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Par")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeeSetId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Yardage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeeSetId", "HoleNumber")
                        .IsUnique();

                    b.ToTable("CourseHoles");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HolesPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("PlayedOn")
                        .HasColumnType("date");

                    b.Property<int>("StartingHole")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeeSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeeSetId");

                    b.HasIndex("UserId");

                    b.ToTable("Rounds", t =>
                        {
                            t.HasCheckConstraint("CK_rounds_holes_played", "\"HolesPlayed\" IN (9, 18)");

                            t.HasCheckConstraint("CK_rounds_starting_hole", "\"StartingHole\" IN (1, 10)");
                        });
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.RoundHole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FairwayResult")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool?>("Gir")
                        .HasColumnType("boolean");

                    b.Property<int>("HoleNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Penalties")
                        .HasColumnType("integer");

                    b.Property<int?>("Putts")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SandShots")
                        .HasColumnType("integer");

                    b.Property<int>("Strokes")
                        .HasColumnType("integer");

                    b.Property<bool?>("UpAndDown")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RoundId", "HoleNumber")
                        .IsUnique();

                    b.ToTable("RoundHoles");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.TeeSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CourseRating")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("SlopeRating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Name")
                        .IsUnique();

                    b.ToTable("TeeSets");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.CourseHole", b =>
                {
                    b.HasOne("GreenBook.Domain.Entities.TeeSet", "TeeSet")
                        .WithMany("Holes")
                        .HasForeignKey("TeeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeeSet");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.Round", b =>
                {
                    b.HasOne("GreenBook.Domain.Entities.Course", "Course")
                        .WithMany("Rounds")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenBook.Domain.Entities.TeeSet", "TeeSet")
                        .WithMany("Rounds")
                        .HasForeignKey("TeeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenBook.Domain.Entities.User", "User")
                        .WithMany("Rounds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("TeeSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.RoundHole", b =>
                {
                    b.HasOne("GreenBook.Domain.Entities.Round", "Round")
                        .WithMany("Holes")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.TeeSet", b =>
                {
                    b.HasOne("GreenBook.Domain.Entities.Course", "Course")
                        .WithMany("TeeSets")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.Course", b =>
                {
                    b.Navigation("Rounds");

                    b.Navigation("TeeSets");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.Round", b =>
                {
                    b.Navigation("Holes");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.TeeSet", b =>
                {
                    b.Navigation("Holes");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("GreenBook.Domain.Entities.User", b =>
                {
                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
